[package]
name = "heater"
version = "0.1.0"
authors = ["Denis Cornehl <denis.cornehl@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.38"
async-recursion = "0.3.1"
clap = "2.33.3"
console = "0.14.0"
counter = "0.5.2"
futures = "0.3.12"
histogram = "0.6.9"
indicatif = "0.15.0"
itertools = "0.10.0"
log = "0.4.13"
num_cpus = "1.13.0"
once_cell = "1.5.2"
pretty_env_logger = "0.4.0"
reqwest = "0.11.0"
sitemap = "0.4.1"
thiserror = "1.0.23"
tokio = {version="1.0.2", features = ["macros", "rt-multi-thread"] }
url = "2.2.0"
xml-rs = "0.8.3"

[dev-dependencies]
mockito = "0.29.0"
test-case = "1.1.0"
